/* SPDX-License-Identifier: GPL-2.0-or-later */
/*
 *  linux/drivers/mmc/host/sdhci-uhs2.h - Secure Digital Host Controller
 *  Interface driver
 *
 * Header file for Host Controller UHS2 related registers and I/O accessors.
 *
 *  Copyright (C) 2014 Intel Corp, All Rights Reserved.
 */
#ifndef __SDHCI_UHS2_H
#define __SDHCI_UHS2_H

#include <linux/bits.h>
#include <linux/iopoll.h>

/*
 * UHS-II Controller registers
 * 0x74 preset in sdhci.h
 * 0x80
 * 0x84-0xB4
 * 0xB8-0xCF
 * 0xE0-0xE7
 */
/* UHS2 */
#define SDHCI_UHS2_BLOCK_SIZE	0x80
#define  SDHCI_UHS2_MAKE_BLKSZ(dma, blksz) \
	((((dma) & 0x7) << 12) | ((blksz) & 0xFFF))

#define SDHCI_UHS2_BLOCK_COUNT	0x84

#define SDHCI_UHS2_CMD_PACKET	0x88
#define  SDHCI_UHS2_CMD_PACK_MAX_LEN	20

#define SDHCI_UHS2_TRANS_MODE	0x9C
#define  SDHCI_UHS2_TRNS_DMA		BIT(0)
#define  SDHCI_UHS2_TRNS_BLK_CNT_EN	BIT(1)
#define  SDHCI_UHS2_TRNS_DATA_TRNS_WRT	BIT(4)
#define  SDHCI_UHS2_TRNS_BLK_BYTE_MODE	BIT(5)
#define  SDHCI_UHS2_TRNS_RES_R5		BIT(6)
#define  SDHCI_UHS2_TRNS_RES_ERR_CHECK_EN	BIT(7)
#define  SDHCI_UHS2_TRNS_RES_INT_DIS	BIT(8)
#define  SDHCI_UHS2_TRNS_WAIT_EBSY	BIT(14)
#define  SDHCI_UHS2_TRNS_2L_HD		BIT(15)

#define SDHCI_UHS2_COMMAND	0x9E
#define  SDHCI_UHS2_COMMAND_SUB_CMD	0x0004
#define  SDHCI_UHS2_COMMAND_DATA	0x0020
#define  SDHCI_UHS2_COMMAND_TRNS_ABORT	0x0040
#define  SDHCI_UHS2_COMMAND_CMD12	0x0080
#define  SDHCI_UHS2_COMMAND_DORMANT	0x00C0
#define  SDHCI_UHS2_COMMAND_PACK_LEN_MASK	GENMASK(12, 8)
#define  SDHCI_UHS2_COMMAND_PACK_LEN_SHIFT	8

#define SDHCI_UHS2_RESPONSE	0xA0
#define  SDHCI_UHS2_RESPONSE_MAX_LEN	20

#define SDHCI_UHS2_MSG_SELECT	0xB4
#define SDHCI_UHS2_MSG_SELECT_CURR	0x0
#define SDHCI_UHS2_MSG_SELECT_ONE	0x1
#define SDHCI_UHS2_MSG_SELECT_TWO	0x2
#define SDHCI_UHS2_MSG_SELECT_THREE	0x3

#define SDHCI_UHS2_MSG		0xB8

#define SDHCI_UHS2_DEV_INT_STATUS	0xBC

#define SDHCI_UHS2_DEV_SELECT	0xBE
#define SDHCI_UHS2_DEV_SELECT_DEV_SEL_MASK	GENMASK(3, 0)
#define SDHCI_UHS2_DEV_SELECT_INT_MSG_EN	BIT(7)

#define SDHCI_UHS2_DEV_INT_CODE	0xBF

#define SDHCI_UHS2_SW_RESET	0xC0
#define SDHCI_UHS2_SW_RESET_FULL	0x0001
#define SDHCI_UHS2_SW_RESET_SD		0x0002

#define SDHCI_UHS2_TIMER_CTRL	0xC2
#define SDHCI_UHS2_TIMER_CTRL_DEADLOCK_SHIFT	4

#define SDHCI_UHS2_ERR_INT_STATUS		0xC4
#define SDHCI_UHS2_ERR_INT_STATUS_EN		0xC8
#define SDHCI_UHS2_ERR_INT_SIG_EN		0xCC
#define SDHCI_UHS2_ERR_INT_STATUS_HEADER	BIT(0)
#define SDHCI_UHS2_ERR_INT_STATUS_RES		BIT(1)
#define SDHCI_UHS2_ERR_INT_STATUS_RETRY_EXP	BIT(2)
#define SDHCI_UHS2_ERR_INT_STATUS_CRC		BIT(3)
#define SDHCI_UHS2_ERR_INT_STATUS_FRAME		BIT(4)
#define SDHCI_UHS2_ERR_INT_STATUS_TID		BIT(5)
#define SDHCI_UHS2_ERR_INT_STATUS_UNRECOVER	BIT(7)
#define SDHCI_UHS2_ERR_INT_STATUS_EBUSY		BIT(8)
#define SDHCI_UHS2_ERR_INT_STATUS_ADMA		BIT(15)
#define SDHCI_UHS2_ERR_INT_STATUS_RES_TIMEOUT	BIT(16)
#define SDHCI_UHS2_ERR_INT_STATUS_DEADLOCK_TIMEOUT	BIT(17)
#define SDHCI_UHS2_ERR_INT_STATUS_VENDOR	BIT(27)
#define SDHCI_UHS2_ERR_INT_STATUS_MASK	\
		(SDHCI_UHS2_ERR_INT_STATUS_HEADER |	\
		SDHCI_UHS2_ERR_INT_STATUS_RES |		\
		SDHCI_UHS2_ERR_INT_STATUS_RETRY_EXP |	\
		SDHCI_UHS2_ERR_INT_STATUS_CRC |		\
		SDHCI_UHS2_ERR_INT_STATUS_FRAME |	\
		SDHCI_UHS2_ERR_INT_STATUS_TID |		\
		SDHCI_UHS2_ERR_INT_STATUS_UNRECOVER |	\
		SDHCI_UHS2_ERR_INT_STATUS_EBUSY |	\
		SDHCI_UHS2_ERR_INT_STATUS_ADMA |	\
		SDHCI_UHS2_ERR_INT_STATUS_RES_TIMEOUT |	\
		SDHCI_UHS2_ERR_INT_STATUS_DEADLOCK_TIMEOUT)
#define SDHCI_UHS2_ERR_INT_STATUS_CMD_MASK	\
		(SDHCI_UHS2_ERR_INT_STATUS_HEADER |	\
		SDHCI_UHS2_ERR_INT_STATUS_RES |		\
		SDHCI_UHS2_ERR_INT_STATUS_FRAME |	\
		SDHCI_UHS2_ERR_INT_STATUS_TID |		\
		SDHCI_UHS2_ERR_INT_STATUS_RES_TIMEOUT)
/* CRC Error occurs during a packet receiving */
#define SDHCI_UHS2_ERR_INT_STATUS_DATA_MASK	\
		(SDHCI_UHS2_ERR_INT_STATUS_RETRY_EXP |	\
		SDHCI_UHS2_ERR_INT_STATUS_CRC |		\
		SDHCI_UHS2_ERR_INT_STATUS_UNRECOVER |	\
		SDHCI_UHS2_ERR_INT_STATUS_EBUSY |	\
		SDHCI_UHS2_ERR_INT_STATUS_ADMA |	\
		SDHCI_UHS2_ERR_INT_STATUS_DEADLOCK_TIMEOUT)

#define SDHCI_UHS2_SET_PTR	0xE0
#define   SDHCI_UHS2_GEN_SET_POWER_LOW		0x0001
#define   SDHCI_UHS2_GEN_SET_N_LANES_POS	8
#define   SDHCI_UHS2_GEN_SET_2L_FD_HD		0x0
#define   SDHCI_UHS2_GEN_SET_2D1U_FD		0x2
#define   SDHCI_UHS2_GEN_SET_1D2U_FD		0x3
#define   SDHCI_UHS2_GEN_SET_2D2U_FD		0x4

#define   SDHCI_UHS2_PHY_SET_SPEED_POS		6
#define   SDHCI_UHS2_PHY_SET_HIBER_EN		BIT(12)
#define   SDHCI_UHS2_PHY_SET_N_LSS_SYN_MASK	GENMASK(19, 16)
#define   SDHCI_UHS2_PHY_SET_N_LSS_SYN_POS	16
#define   SDHCI_UHS2_PHY_SET_N_LSS_DIR_MASK	GENMASK(23, 20)
#define   SDHCI_UHS2_PHY_SET_N_LSS_DIR_POS	20

#define   SDHCI_UHS2_TRAN_SET_N_FCU_MASK	GENMASK(15, 8)
#define   SDHCI_UHS2_TRAN_SET_N_FCU_POS		8
#define   SDHCI_UHS2_TRAN_SET_RETRY_CNT_MASK	GENMASK(17, 16)
#define   SDHCI_UHS2_TRAN_SET_RETRY_CNT_POS	16

#define   SDHCI_UHS2_TRAN_SET_1_N_DAT_GAP_MASK	GENMASK(7, 0)

#define SDHCI_UHS2_HOST_CAPS_PTR	0xE2
#define  SDHCI_UHS2_HOST_CAPS_GEN_OFFSET	0
#define   SDHCI_UHS2_HOST_CAPS_GEN_DAP_MASK	GENMASK(3, 0)
#define   SDHCI_UHS2_HOST_CAPS_GEN_GAP_MASK	GENMASK(7, 4)
#define   SDHCI_UHS2_HOST_CAPS_GEN_GAP(gap)	((gap) * 360)
#define SDHCI_UHS2_HOST_CAPS_GEN_GAP_SHIFT 4
#define   SDHCI_UHS2_HOST_CAPS_GEN_LANE_MASK	GENMASK(13, 8)
#define   SDHCI_UHS2_HOST_CAPS_GEN_LANE_SHIFT	8
#define    SDHCI_UHS2_HOST_CAPS_GEN_2L_HD_FD	1
#define    SDHCI_UHS2_HOST_CAPS_GEN_2D1U_FD	2
#define    SDHCI_UHS2_HOST_CAPS_GEN_1D2U_FD	4
#define    SDHCI_UHS2_HOST_CAPS_GEN_2D2U_FD	8
#define   SDHCI_UHS2_HOST_CAPS_GEN_ADDR_64	BIT(14)
#define   SDHCI_UHS2_HOST_CAPS_GEN_BOOT		BIT(15)
#define   SDHCI_UHS2_HOST_CAPS_GEN_DEV_TYPE_MASK	GENMASK(17, 16)
#define   SDHCI_UHS2_HOST_CAPS_GEN_DEV_TYPE_SHIFT	16
#define    SDHCI_UHS2_HOST_CAPS_GEN_DEV_TYPE_RMV	0
#define    SDHCI_UHS2_HOST_CAPS_GEN_DEV_TYPE_EMB	1
#define    SDHCI_UHS2_HOST_CAPS_GEN_DEV_TYPE_EMB_RMV	2
#define   SDHCI_UHS2_HOST_CAPS_GEN_NUM_DEV_MASK		GENMASK(21, 18)
#define   SDHCI_UHS2_HOST_CAPS_GEN_NUM_DEV_SHIFT	18
#define   SDHCI_UHS2_HOST_CAPS_GEN_BUS_TOPO_MASK	GENMASK(23, 22)
#define   SDHCI_UHS2_HOST_CAPS_GEN_BUS_TOPO_SHIFT	22
#define   SDHCI_UHS2_HOST_CAPS_GEN_BUS_TOPO_P2P		0
#define   SDHCI_UHS2_HOST_CAPS_GEN_BUS_TOPO_RING	1
#define   SDHCI_UHS2_HOST_CAPS_GEN_BUS_TOPO_HUB		2
#define   SDHCI_UHS2_HOST_CAPS_GEN_BUS_TOPO_HUB_RING	3

#define  SDHCI_UHS2_HOST_CAPS_PHY_OFFSET	4
#define   SDHCI_UHS2_HOST_CAPS_PHY_REV_MASK		GENMASK(5, 0)
#define   SDHCI_UHS2_HOST_CAPS_PHY_RANGE_MASK		GENMASK(7, 6)
#define   SDHCI_UHS2_HOST_CAPS_PHY_RANGE_SHIFT		6
#define   SDHCI_UHS2_HOST_CAPS_PHY_RANGE_A		0
#define   SDHCI_UHS2_HOST_CAPS_PHY_RANGE_B		1
#define   SDHCI_UHS2_HOST_CAPS_PHY_N_LSS_SYN_MASK	GENMASK(19, 16)
#define   SDHCI_UHS2_HOST_CAPS_PHY_N_LSS_SYN_SHIFT	16
#define   SDHCI_UHS2_HOST_CAPS_PHY_N_LSS_DIR_MASK	GENMASK(23, 20)
#define   SDHCI_UHS2_HOST_CAPS_PHY_N_LSS_DIR_SHIFT	20
#define  SDHCI_UHS2_HOST_CAPS_TRAN_OFFSET	8
#define   SDHCI_UHS2_HOST_CAPS_TRAN_LINK_REV_MASK	GENMASK(5, 0)
#define   SDHCI_UHS2_HOST_CAPS_TRAN_N_FCU_MASK		GENMASK(15, 8)
#define   SDHCI_UHS2_HOST_CAPS_TRAN_N_FCU_SHIFT		8
#define   SDHCI_UHS2_HOST_CAPS_TRAN_HOST_TYPE_MASK	GENMASK(18, 16)
#define   SDHCI_UHS2_HOST_CAPS_TRAN_HOST_TYPE_SHIFT	16
#define   SDHCI_UHS2_HOST_CAPS_TRAN_BLK_LEN_MASK	GENMASK(31, 20)
#define   SDHCI_UHS2_HOST_CAPS_TRAN_BLK_LEN_SHIFT	20

#define  SDHCI_UHS2_HOST_CAPS_TRAN_1_OFFSET	12
#define  SDHCI_UHS2_HOST_CAPS_TRAN_1_N_DATA_GAP_MASK	GENMASK(7, 0)

#define SDHCI_UHS2_TEST_PTR	0xE4
#define  SDHCI_UHS2_TEST_ERR_HEADER	BIT(0)
#define  SDHCI_UHS2_TEST_ERR_RES	BIT(1)
#define  SDHCI_UHS2_TEST_ERR_RETRY_EXP	BIT(2)
#define  SDHCI_UHS2_TEST_ERR_CRC	BIT(3)
#define  SDHCI_UHS2_TEST_ERR_FRAME	BIT(4)
#define  SDHCI_UHS2_TEST_ERR_TID	BIT(5)
#define  SDHCI_UHS2_TEST_ERR_UNRECOVER	BIT(7)
#define  SDHCI_UHS2_TEST_ERR_EBUSY	BIT(8)
#define  SDHCI_UHS2_TEST_ERR_ADMA	BIT(15)
#define  SDHCI_UHS2_TEST_ERR_RES_TIMEOUT	BIT(16)
#define  SDHCI_UHS2_TEST_ERR_DEADLOCK_TIMEOUT	BIT(17)
#define  SDHCI_UHS2_TEST_ERR_VENDOR	BIT(27)

#define SDHCI_UHS2_EMBED_CTRL	0xE6
#define SDHCI_UHS2_VENDOR	0xE8

struct sdhci_host;

void sdhci_uhs2_dump_regs(struct sdhci_host *host);
bool sdhci_uhs2_mode(struct sdhci_host *host);
void sdhci_uhs2_reset(struct sdhci_host *host, u16 mask);
void sdhci_uhs2_set_power(struct sdhci_host *host, unsigned char mode,
			  unsigned short vdd);
void sdhci_uhs2_set_timeout(struct sdhci_host *host, struct mmc_command *cmd);
void sdhci_uhs2_clear_set_irqs(struct sdhci_host *host, u32 clear, u32 set);
void sdhci_uhs2_request(struct mmc_host *mmc, struct mmc_request *mrq);
int sdhci_uhs2_request_atomic(struct mmc_host *mmc, struct mmc_request *mrq);
u32 sdhci_uhs2_irq(struct sdhci_host *host, u32 intmask);
int sdhci_uhs2_add_host(struct sdhci_host *host);
void sdhci_uhs2_remove_host(struct sdhci_host *host, int dead);

#endif /* __SDHCI_UHS2_H */
